version: "3.9"
services:
  web:
    build: .
    container_name: intelligence-web
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "80:80"

  redis:
    container_name: intelligence-redis
    image: redis:alpine

  db:
    image: postgres:alpine
    container_name: intelligence-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
